version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:aidalox2011@db:5432/task6

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task6
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aidalox2011
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
